sudo: false
language: c

addons:
  apt:
    packages:
    - libgmp-dev

before_install:
# stack
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
#- cd ~/.local/bin
#- travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v1.1.2/stack-1.1.2-linux-x86_64.tar.gz | tar xzvf -
#- mv stack-1.1.2-linux-x86_64/stack stack
#- chmod a+x ~/.local/bin/stack
- travis_retry curl -L https://www.stackage.com/stack/linux-x86_64 | tar xz --wildcards --strip-components==1 -C ~/local/bin '*/stack'

script:
- stack --no-terminal setup
- stack --no-terminal build
- stack --no-terminal test

cache:
  directories:
  - $HOME/.stack
