sudo: false
language: c

addons:
  apt:
    packages:
    - libgmp-dev

before_install:
# stack
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v1.1.2/stack-1.1.2-linux-x86_64.tar.gz | gunzip | tar xvf - > ~/.local/bin/stack
- chmod a+x ~/.local/bin/stack

script:
- stack --no-terminal setup
- stack --no-terminal build
- stack --no-terminal test

cache:
  directories:
  - $HOME/.stack
